name: CICD Auto-Issue
title: 'CICD Auto-Issue on {{ date | date("ddd, MMM Do at HH mm ss") }}'
description: 'Auto-creates an issue with details about the failed CICD workflow.'
assignees: 
  - 'KemingHe'
  - '{{ github.event.workflow_run.head_commit.author.name }}'
labels: 
  - 'bug'
  - 'CICD'
projects:
  - 'DEV Event Feed Product Launch'
body: 
  - type: markdown
    id: failure-details
    attributes:
      value: |
        Hi there,

        A CICD workflow failed on branch: {{ github.event.workflow_run.head_branch }}. 
        
        Here are more details:

        - Workflow: {{ github.event.workflow_run.name }}
        - Run: {{ github.event.workflow_run.html_url }}
        - Commit: {{ github.event.workflow_run.head_commit.url }}
        - Commit message: {{ github.event.workflow_run.head_commit.message }}
        - Author: {{ github.event.workflow_run.head_commit.author.name }} ({{ github.event.workflow_run.head_commit.author.email }})

        Please investigate and fix as soon as you can. Reach out if you need help.

        Best,
        Keming He and GitHub Actions

  - type: dropdown
    id: failure-origin
    attributes:
      label: 'Where did the failure originate?'
      multiple: true
      options:
        - 'I pushed my code and tests failed.'
        - 'I merged someone else''s code and tests failed.'
        - 'I reinstalled dependencies and tests failed.'
        - 'I don''t know, but I will ask for help in Discord.'
