# ./.github/workflows/ci-dev-lead.yml
#
# Auto code review for dev-lead-trevor branch.
name: Dev Lead CI

on:
  push:
    branches:
      - 'dev-lead-trevor'
  pull_request:
    branches:
      - 'dev-lead-trevor'
  
permissions:
  contents: read
  pull-requests: read

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/ci-common.yml
        with:
          branch_name: 'dev-lead-trevor'
