# ./.github/workflows/ci-dev-main.yml
#
# Auto code review for main branch.
name: Main CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  # Schedule auto review main branch every Sunday and Wednesday.
  schedule:
    - cron: '0 0 * * 0'
    - cron: '0 0 * * 3'
  
permissions:
  contents: read
  pull-requests: read

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/ci-common.yml
        with:
          branch_name: 'main'
