# ./.github/workflows/ci-prod.yml
#
# Auto code review for production branch.
name: Prod CI

on:
  push:
    branches:
      - 'production'
  pull_request:
    branches:
      - 'production'
  # Allow manual trigger.
  workflow_dispatch:
  # Schedule auto review prod branch every day.
  schedule:
    - cron: '0 0 * * *'
  
permissions:
  contents: read
  pull-requests: read

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/ci-common.yml
    with:
      branch_name: ${{ github.ref }}
