# ./.github/workflows/cicd-issue-create.yml
#
# Auto-creates an issue when CICD workflow fails.

name: Create CICD Failure Issue

on:
  workflow_run:
    workflows:
      - '*'
    types:
      - completed

permissions:
  contents: read
  issues: write

jobs:
  create-issue:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Create issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: './.github/ISSUE_TEMPLATE/cicd-issue-template.md'
          update_existing: true
          search_existing: all
