name: Playwright E2E

# Enabling workflow to run on all push, PR, and manual triggers.
on:
  [push, pull_request, workflow_dispatch]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      # Check out code and setup Node.js,
      # using main instead of specific version
      # to always use the latest release, assuming well-maintained.
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm install -g pnpm && pnpm install

    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps

    - name: Run Playwright tests
      run: pnpm exec playwright test

    - uses: actions/upload-artifact@main
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7
    
