name: GCloud Deploy

on:
  push:
    branches: [ 'production' ]
  pull_request:
    branches: [ 'production' ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
